"""
The three email templates from the changes document.

Recipients are School Admins (principals), Program Coordinators and Thinking
Coaches. Expected volume is 150-200 emails per year.

Students and Parents are never emailed: their login IDs are generated by the
system and handed over by the school, and neither role can change its own
password. ``settings.EMAIL_SUPPRESSED_ROLES`` holds that list and ``_send``
enforces it, so every send in the project passes the same gate -- including
callers that write their own body via ``send_raw``.

  1. Onboarding            welcome message carrying login credentials
  2. Announcement / event  update notification
  3. Password reset        reset link with school and role

Wording follows the document. Placeholders are filled from real records rather
than left in the message, and a missing value is dropped from the email instead
of being sent as an empty line.

Every send is best-effort: a mail failure is logged and never aborts whatever the
caller was doing. Onboarding must not fail because a mail server is unreachable.
"""

import logging

from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string

logger = logging.getLogger('enpower.email')

# Branded HTML lives in competencies/templates/emails/. Every message goes out
# as multipart/alternative: the plain-text body built below stays the fallback,
# so a text-only client still gets a readable email.
#
# The header logo is fetched over HTTPS. It used to travel as an inline cid:
# attachment, which rendered correctly but made Gmail print an
# "enpower-logo.png" chip under every message in the inbox list -- it counts any
# attached part, inline or not. A hosted URL has no chip; with images blocked
# the alt text carries the name.
LOGO_STATIC_PATH = 'assets/images/email-badge.png'

ROLE_LABELS = {
    'SCHOOL_ADMIN': 'School Admin',
    'THINKING_COACH': 'Thinking Coach',
    'PROGRAM_COORDINATOR': 'Program Coordinator',
    'SUPER_ADMIN': 'Super Admin',
    'STUDENT': 'Student',
    'PARENT': 'Parent',
}

SIGN_OFF = 'Warm regards,\nTeam ENpower Skill Lab'

# Shown as a short list in the onboarding email. Each line names something the
# role can actually reach today -- promising a screen that does not exist is
# worse than saying nothing, so this list is trimmed, not aspirational.
DASHBOARD_POINTS = {
    'SCHOOL_ADMIN': [
        'View grade-wise reports for your school',
        'Track class performance and project completion',
        'Monitor attendance across grades',
        'Download the full school report as Excel',
    ],
    'THINKING_COACH': [
        'Enter assessment scores for your students',
        'Generate project and annual Skill Passport reports',
        'Mark and review class attendance',
        'See announcements and the event calendar',
    ],
    'PROGRAM_COORDINATOR': [
        'Monitor every school mapped to you',
        'Track project progress and completion',
        'View grade-wise programme reports',
    ],
    'SUPER_ADMIN': [
        'Manage schools, frameworks, projects and users',
        'Onboard staff individually or in bulk',
        'View platform-wide reports and analytics',
    ],
}


def dashboard_points(role):
    return DASHBOARD_POINTS.get(normalise_role(role), [
        'View your reports and progress',
        'See announcements and upcoming events',
    ])


def role_label(role):
    return ROLE_LABELS.get(normalise_role(role), (role or 'User').replace('_', ' ').title())


def normalise_role(role):
    """Reduce a role to its code, whoever wrote it.

    Callers pass this in three shapes — the model's ``THINKING_COACH``, the
    bulk importer's display label ``Thinking Coach``, and occasionally the
    lowercase sheet key. All three have to reach the same gate below, so they
    are folded to one form here rather than at each call site.
    """
    return (role or '').strip().upper().replace(' ', '_').replace('-', '_')


def is_suppressed(role):
    """True when this role is not to be emailed.

    Students and Parents get system-generated login IDs handed over by the
    school; no credential mail is sent to them. Kept as a settings value so the
    list is one place, not a condition repeated at every send.
    """
    return normalise_role(role) in getattr(settings, 'EMAIL_SUPPRESSED_ROLES', set())


def _lines(*parts):
    """Join message parts, dropping any that resolved to nothing.

    A blank school or programme would otherwise send "School:" with nothing
    after it, which reads worse than omitting the line.
    """
    return '\n'.join(p for p in parts if p)


def send_raw(subject, body, to, role):
    """Send a message that does not use one of the three templates.

    Same suppression gate as everything else, so a caller writing its own body
    cannot accidentally mail a Student or Parent.
    """
    return _send(subject, body, to, role=role)


def _login_url():
    site = (getattr(settings, 'SITE_URL', '') or '').rstrip('/')
    return f'{site}/login/' if site else ''


def _base_context(role=None, school_name=None, program_name=None, **extra):
    """Values every template needs, so no child has to rebuild them."""
    site_url = (getattr(settings, 'SITE_URL', '') or '').rstrip('/')
    static_prefix = (settings.STATIC_URL or 'static/').strip('/')
    ctx = {
        'role_label': role_label(role),
        'school_name': school_name,
        'programme': program_name or 'ENpower Skill Lab',
        'site_url': site_url,
        # The bare host reads better inside a sentence than the full URL.
        'site_url_label': site_url.split('://', 1)[-1],
        'badge_url': f'{site_url}/{static_prefix}/{LOGO_STATIC_PATH}' if site_url else '',
    }
    ctx.update(extra)
    return ctx


def _send(subject, body, to, role=None, template=None, context=None):
    """Send one message, gated by role.

    ``body`` is the plain-text version and is always sent. When ``template`` is
    given, the branded HTML is attached alongside it and the client picks.
    """
    if not to:
        return False
    if is_suppressed(role):
        logger.info('Email suppressed for %s (%s): %s',
                    to, role_label(role), subject)
        return False
    try:
        message = EmailMultiAlternatives(
            subject=subject, body=body,
            from_email=settings.DEFAULT_FROM_EMAIL, to=[to])

        if template:
            ctx = dict(context or {})
            ctx.setdefault('subject', subject)
            message.attach_alternative(
                render_to_string(f'emails/{template}', ctx), 'text/html')

        message.send(fail_silently=False)
        return True
    except Exception as e:
        logger.error('Email FAILED to %s (%s): %s: %s', to, subject, type(e).__name__, e)
        return False


# ── 1. Onboarding ───────────────────────────────────────────────────────

def send_onboarding(to, name, login_id, password, role,
                    school_name=None, program_name=None):
    """Welcome message with credentials, sent when an account is created."""
    programme = program_name or 'ENpower Skill Lab'
    label = role_label(role)

    where = f' for {school_name}' if school_name else ''
    body = _lines(
        f'Dear {name},',
        '',
        f'Welcome to {programme} – ENpower Skill Lab!',
        '',
        f'You have been onboarded as {label}{where}.',
        '',
        'Your login credentials are:',
        f'Login ID: {login_id}',
        f'One-Time Password: {password}',
        '',
        f'Log in: {_login_url()}' if _login_url() else '',
        '',
        'Please log in using the above credentials and reset your password '
        'after your first login.',
        '',
        SIGN_OFF,
    )
    return _send(
        f'Welcome to ENpower Skill Lab — {label} Account', body, to, role=role,
        template='onboarding.html',
        context=_base_context(role, school_name, program_name,
                              name=name, login_id=login_id, password=password,
                              dashboard_points=dashboard_points(role),
                              preheader=f'Your {label} login for {programme}'))


# ── 2. Announcement / event / newsletter ────────────────────────────────

def send_announcement(to, name, title, details, role,
                      school_name=None, program_name=None):
    """Update notification for an announcement, event or newsletter."""
    programme = program_name or 'ENpower Skill Lab'

    body = _lines(
        f'Dear {name},',
        '',
        f'Here’s an important update for {programme}.',
        '',
        title or 'Update',
        details or '',
        '',
        f'Program: {programme}',
        f'School: {school_name}' if school_name else '',
        f'Your Role: {role_label(role)}',
        '',
        'For more details, please log in to your ENpower Skill Lab dashboard.',
        '',
        SIGN_OFF,
    )
    return _send(
        title or 'ENpower Skill Lab — Update', body, to, role=role,
        template='announcement.html',
        context=_base_context(role, school_name, program_name,
                              name=name, title=title or 'Update', details=details or '',
                              preheader=f'An update for {programme}'))


def send_announcement_bulk(announcement, recipients):
    """Send one announcement to many users. Returns how many were sent.

    Each recipient gets their own school and role in the body, so the message
    reads correctly whoever opens it.
    """
    title = (getattr(announcement, 'event_name', None)
             or getattr(announcement, 'newsletter_month', None)
             or getattr(announcement, 'story_student_name', None)
             or 'Update')
    details = (getattr(announcement, 'event_description', None)
               or getattr(announcement, 'story_text', None) or '')

    sent = 0
    for user, school_name, program_name in recipients:
        name = user.get_full_name() or user.username
        if send_announcement(user.email, name, title, details,
                             getattr(user, 'role', None), school_name, program_name):
            sent += 1
    return sent


# ── 3. Password reset ───────────────────────────────────────────────────

def send_password_reset(to, name, reset_link, role,
                        school_name=None, program_name=None):
    """Confirmation of a reset request, carrying the reset link."""
    programme = program_name or 'ENpower Skill Lab'

    body = _lines(
        f'Dear {name},',
        '',
        f'Your password reset request for {programme} – ENpower Skill Lab has '
        f'been received.',
        '',
        f'School: {school_name}' if school_name else '',
        f'Your Role: {role_label(role)}',
        '',
        'Please use the link below to reset your password:',
        f'Reset Password: {reset_link}',
        '',
        'If you did not request this, please ignore this email.',
        '',
        SIGN_OFF,
    )
    return _send(
        'Password Reset — ENpower Skill Lab', body, to, role=role,
        template='password_reset.html',
        context=_base_context(role, school_name, program_name,
                              name=name, reset_link=reset_link,
                              preheader='Reset your ENpower Skill Lab password'))
