# Generated by Django 5.2.4 on 2026-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0012_studentprojectfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillar',
            name='is_kb',
            field=models.BooleanField(default=False, help_text='Kaushal Bodh pillar — scores only, excluded from passport/profiling calculations'),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='color',
            field=models.CharField(choices=[('teal', 'Teal'), ('purple', 'Purple'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('red', 'Red')], max_length=20),
        ),
    ]
