# Generated by Django 5.2.4 on 2026-05-08 06:24

from django.db import migrations


def seed_kb_pillar(apps, schema_editor):
    Pillar = apps.get_model('competencies', 'Pillar')

    # Only create if KB pillar doesn't exist yet
    if not Pillar.objects.filter(is_kb=True).exists():
        Pillar.objects.create(
            name='Kaushal Bodh',
            number='06',
            color='red',
            order=6,
            is_kb=True,
        )


def reverse_kb_pillar(apps, schema_editor):
    Pillar = apps.get_model('competencies', 'Pillar')
    Pillar.objects.filter(is_kb=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0013_add_kb_flag_to_pillar'),
    ]

    operations = [
        migrations.RunPython(seed_kb_pillar, reverse_kb_pillar),
    ]
