# Generated by Django 5.2.4 on 2026-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0014_seed_kb_pillar'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillar',
            name='framework',
            field=models.CharField(choices=[('FSL', 'FSL — Foundational Skill Lab'), ('CSL', 'CSL+ — Custom Skill Lab')], default='FSL', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('FSL', 'FSL — Foundational Skill Lab'), ('CSL', 'CSL+ — Custom Skill Lab')], default='FSL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='color',
            field=models.CharField(choices=[('teal', 'Teal'), ('purple', 'Purple'), ('blue', 'Blue'), ('orange', 'Orange'), ('green', 'Green'), ('red', 'Red'), ('pink', 'Pink'), ('indigo', 'Indigo'), ('amber', 'Amber')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
