# Generated by Django 5.2.4 on 2026-05-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0016_seed_csl_pillars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('prefix', models.CharField(max_length=20, unique=True)),
                ('is_fixed', models.BooleanField(default=False, help_text='Fixed frameworks have read-only pillars (e.g. FSL)')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='pillar',
            name='framework',
            field=models.CharField(blank=True, default='FSL', max_length=10),
        ),
        migrations.AlterField(
            model_name='pillar',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, default='FSL', max_length=10),
        ),
        migrations.AddField(
            model_name='pillar',
            name='framework_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pillars', to='competencies.framework'),
        ),
        migrations.AddField(
            model_name='project',
            name='framework_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='competencies.framework'),
        ),
    ]
