# Generated by Django 5.2.8 on 2026-06-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0018_seed_frameworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESLProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Program Title')),
                ('description', models.TextField(blank=True, verbose_name='Description of the Program')),
                ('competencies_description', models.TextField(blank=True, help_text='Competencies applicable at program level', verbose_name='Competencies')),
                ('applicable_grades', models.JSONField(blank=True, default=list, help_text='e.g. [1,2,6,7,8]', verbose_name='Grades Applicable')),
                ('applicable_boards', models.JSONField(blank=True, default=list, help_text='e.g. ["CBSE","ICSE"]', verbose_name='Boards Applicable')),
                ('program_document', models.FileField(blank=True, null=True, upload_to='esl_products/', verbose_name='Program Document (SKU/Concept Note/Brochure)')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Draft', 'Draft')], default='Draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ESL Product',
                'verbose_name_plural': 'ESL Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('grade', models.CharField(blank=True, max_length=5, verbose_name='Grade')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('esl_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='competencies.eslproduct')),
            ],
            options={
                'ordering': ['esl_product', 'grade', 'project_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200, verbose_name='Session Title')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Brief Session Descriptor')),
                ('product_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='competencies.productproject')),
            ],
            options={
                'ordering': ['product_project', 'session_number'],
            },
        ),
    ]
