# Generated by Django 5.2.8 on 2026-06-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0019_add_esl_product'),
        ('schools', '0008_add_exceptions_events_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_type', models.CharField(choices=[('event', 'Event'), ('newsletter', 'Newsletter'), ('success_story', 'Student Success Story')], max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_grades', models.JSONField(blank=True, default=list)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_description', models.TextField(blank=True)),
                ('event_link', models.URLField(blank=True)),
                ('publish_to', models.JSONField(blank=True, default=list, help_text='e.g. ["school","student","parent"]')),
                ('newsletter_date', models.DateField(blank=True, null=True)),
                ('newsletter_month', models.CharField(blank=True, max_length=20)),
                ('newsletter_file', models.FileField(blank=True, null=True, upload_to='newsletters/')),
                ('newsletter_weblink', models.URLField(blank=True)),
                ('story_student_name', models.CharField(blank=True, max_length=100)),
                ('story_grade', models.CharField(blank=True, max_length=10)),
                ('story_text', models.CharField(blank=True, max_length=500)),
                ('story_photo_1', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('story_photo_2', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('story_youtube_link', models.URLField(blank=True)),
                ('applicable_schools', models.ManyToManyField(blank=True, related_name='announcements', to='schools.school')),
                ('esl_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='competencies.eslproduct')),
                ('story_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
