# Generated by Django 6.0.6 on 2026-06-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0020_add_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band1_text', models.TextField(blank=True, help_text='1-4 Not meeting expectations')),
                ('band2_text', models.TextField(blank=True, help_text='4-7 Approaching expectation')),
                ('band3_text', models.TextField(blank=True, help_text='7-9 Fully meeting expectation')),
                ('band4_text', models.TextField(blank=True, help_text='9-10 Exceeding expectation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='competencies.assessment')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='competencies.competency')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('assessment', 'competency')},
            },
        ),
    ]
