# Generated by Django 6.0.6 on 2026-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0021_rubriccriterion'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='program',
            field=models.CharField(blank=True, choices=[('fsl', 'Future Skills Lab'), ('csl_plus_pc', 'CSL Plus with PC'), ('csl_plus_tc', 'CSL Plus with TC'), ('csl_foundation_pc', 'CSL Foundation with PC'), ('csl_foundation', 'CSL Foundation')], max_length=20, null=True),
        ),
    ]
