# Generated by Django 5.2.16 on 2026-07-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencies", "0022_announcement_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="publish_to",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Target roles, e.g. ["student","parent","teacher","coordinator","school_admin"]',
            ),
        ),
    ]
