# Generated by Django 5.2.8 on 2026-08-24 10:11

from django.db import migrations, models


# Projects used to store a whole stage ("Middle" = classes 6–8). They now store
# one individual grade, so each legacy value collapses to the lowest grade of
# its stage. A stage cannot be split across three projects automatically, so
# anything that should target a different grade must be re-set by hand.
STAGE_TO_LOWEST_GRADE = {
    'Foundational': '1',
    'Preparatory':  '3',
    'Middle':       '6',
    'Secondary':    '9',
}


def stages_to_grades(apps, schema_editor):
    Project = apps.get_model('competencies', 'Project')
    for stage, grade in STAGE_TO_LOWEST_GRADE.items():
        Project.objects.filter(grade=stage).update(grade=grade)


def grades_to_stages(apps, schema_editor):
    """Reverse: map each grade back to the stage that contains it."""
    Project = apps.get_model('competencies', 'Project')
    grade_to_stage = {
        '1': 'Foundational', '2': 'Foundational',
        '3': 'Preparatory',  '4': 'Preparatory',  '5': 'Preparatory',
        '6': 'Middle',       '7': 'Middle',       '8': 'Middle',
        '9': 'Secondary',    '10': 'Secondary',   '11': 'Secondary', '12': 'Secondary',
    }
    for grade, stage in grade_to_stage.items():
        Project.objects.filter(grade=grade).update(grade=stage)


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0023_alter_announcement_publish_to'),
    ]

    operations = [
        migrations.RunPython(stages_to_grades, grades_to_stages),
        migrations.AlterField(
            model_name='project',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], help_text='Individual grade this project runs for (1–12).', max_length=20),
        ),
    ]
