# Generated by Django 5.2.8 on 2026-08-26 06:43

from django.db import migrations, models

# Spec slide 8/9 narrows the Type dropdown to Presentation / Written /
# Oral-Portfolio. Existing rows carry the old labels, so map them across
# rather than leaving values that no longer validate.
TYPE_MAP = {
    'Written Assignment': 'Written',
    'Lab Report':         'Written',
    'Peer Review':        'Oral/Portfolio',
}
REVERSE_MAP = {
    'Written':        'Written Assignment',
    'Oral/Portfolio': 'Peer Review',
}


def migrate_types(apps, schema_editor):
    Assessment = apps.get_model('competencies', 'Assessment')
    for old, new in TYPE_MAP.items():
        Assessment.objects.filter(assessment_type=old).update(assessment_type=new)


def reverse_types(apps, schema_editor):
    Assessment = apps.get_model('competencies', 'Assessment')
    for new, old in REVERSE_MAP.items():
        Assessment.objects.filter(assessment_type=new).update(assessment_type=old)


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0024_project_grade_individual'),
    ]

    operations = [
        migrations.RunPython(migrate_types, reverse_types),
        migrations.AddField(
            model_name='projectreport',
            name='common_strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Presentation', 'Presentation'), ('Written', 'Written'), ('Oral/Portfolio', 'Oral/Portfolio')], default='Presentation', max_length=30),
        ),
    ]
