# Generated by Django 5.2.8 on 2026-09-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0027_seed_eight_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='has_kaushal_bodh',
            field=models.BooleanField(default=True, help_text='Show the Kaushal Bodh report for this framework'),
        ),
    ]


def turn_off_for_fsl(apps, schema_editor):
    """FSL records no Kaushal Bodh scores at all, so the report is empty there.

    Default True for everything else: CSL+ and CSL Foundation both use it, and
    a framework added later should show it until someone says otherwise.
    """
    Framework = apps.get_model('competencies', 'Framework')
    Framework.objects.filter(has_profiling=True).update(has_kaushal_bodh=False)


def noop(apps, schema_editor):
    pass


Migration.operations.append(migrations.RunPython(turn_off_for_fsl, noop))
