# Generated by Django 6.0.6 on 2026-08-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_move_parent_from_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
