# Generated by Django 5.2.8 on 2026-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_alter_parent_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
