# Generated by Django 5.2.4 on 2026-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='framework_type',
            field=models.CharField(choices=[('FSL', 'FSL — Foundational Skill Lab'), ('CSL', 'CSL+ — Custom Skill Lab')], default='FSL', help_text='Select which skill framework this school follows', max_length=10, verbose_name='Skill Framework'),
        ),
    ]
