# Generated by Django 5.2.4 on 2026-05-08 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0017_dynamic_framework'),
        ('schools', '0004_add_framework_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='framework_ref',
            field=models.ForeignKey(blank=True, help_text='Select which skill framework this school follows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='competencies.framework', verbose_name='Skill Framework'),
        ),
        migrations.AlterField(
            model_name='school',
            name='framework_type',
            field=models.CharField(blank=True, default='FSL', max_length=10),
        ),
    ]
