# Generated by Django 5.2.8 on 2026-06-25 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_dynamic_framework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grade_wise_students',
            field=models.JSONField(blank=True, default=dict, help_text='JSON: {"1": 60, "2": 55, ...}', verbose_name='Grade-wise Number of Students'),
        ),
        migrations.AddField(
            model_name='school',
            name='program_academic_year',
            field=models.CharField(blank=True, help_text='e.g. 2026-27', max_length=20, null=True, verbose_name='Program Academic Year'),
        ),
        migrations.AddField(
            model_name='school',
            name='skill_program',
            field=models.CharField(blank=True, choices=[('fsl', 'Future Skills Lab'), ('csl_plus_pc', 'CSL Plus with PC'), ('csl_plus_tc', 'CSL Plus with TC'), ('csl_foundation_pc', 'CSL Foundation with PC'), ('csl_foundation', 'CSL Foundation')], help_text='Select the ESL product assigned to this school', max_length=20, null=True, verbose_name='Skill Program (ESL Product)'),
        ),
        migrations.AddField(
            model_name='school',
            name='srm',
            field=models.ForeignKey(blank=True, help_text='Assign a Program Coordinator as SRM', limit_choices_to={'role': 'PROGRAM_COORDINATOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='srm_schools', to=settings.AUTH_USER_MODEL, verbose_name='School Relationship Manager (SRM)'),
        ),
        migrations.AddField(
            model_name='school',
            name='trainer_assigned',
            field=models.ForeignKey(blank=True, help_text='Assign a Thinking Coach as trainer', limit_choices_to={'role': 'THINKING_COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_schools', to=settings.AUTH_USER_MODEL, verbose_name='Trainer Assigned'),
        ),
    ]
