# Generated by Django 5.2.8 on 2026-06-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_add_skill_program_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='go_live_certificate',
            field=models.FileField(blank=True, null=True, upload_to='go_live_certs/', verbose_name='Go-Live Certificate'),
        ),
        migrations.AddField(
            model_name='school',
            name='lab_fees_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total lab fees including GST', max_digits=12, null=True, verbose_name='Lab Fees (with GST)'),
        ),
        migrations.AddField(
            model_name='school',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('annual', 'Annual')], max_length=20, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='school',
            name='program_fees_with_gst',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total program fees including GST', max_digits=12, null=True, verbose_name='Program Fees (with GST)'),
        ),
        migrations.AddField(
            model_name='school',
            name='signed_agreement',
            field=models.FileField(blank=True, null=True, upload_to='school_agreements/', verbose_name='Signed TCE School Agreement'),
        ),
        migrations.AddField(
            model_name='school',
            name='tce_sales_spoc_contact',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TCE Sales SPOC Contact'),
        ),
        migrations.AddField(
            model_name='school',
            name='tce_sales_spoc_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TCE Sales SPOC Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing Email'),
        ),
    ]
