# Generated by Django 5.2.8 on 2026-06-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_add_fees_commercial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='events_workshop_calendar',
            field=models.JSONField(blank=True, default=list, help_text='List of events: [{"date": "2026-08-15", "event": "Independence Day"}, ...]', verbose_name='Events & Workshop Calendar'),
        ),
        migrations.AddField(
            model_name='school',
            name='exceptions_for_school',
            field=models.TextField(blank=True, help_text='Any special exceptions or notes for this school', null=True, verbose_name='Exceptions for this School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='events_calendar',
            field=models.TextField(blank=True, null=True, verbose_name='Events & Workshops Calendar (Legacy)'),
        ),
    ]
