# Generated by Django 6.0.6 on 2026-06-30 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_add_exceptions_events_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='thinking_coach',
            field=models.ForeignKey(blank=True, help_text='Assigned thinking coach for this class', limit_choices_to={'role': 'THINKING_COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to=settings.AUTH_USER_MODEL, verbose_name='Thinking Coach'),
        ),
    ]
