# Generated by Django 5.2.8 on 2026-10-07 11:18

import enpower_skill_lab.academic_year
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_class_rows_for_existing_timetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], default=enpower_skill_lab.academic_year.current_academic_year, help_text='Academic year for this class', max_length=9, verbose_name='Academic Year'),
        ),
    ]
