# Generated by Django 5.2.8 on 2026-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_move_student_from_superadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gr_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
