# Generated by Django 5.2.8 on 2026-09-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_gr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_email',
            field=models.EmailField(max_length=254),
        ),
    ]
