
"""
Django settings for enpower_skill_lab project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets (SMTP credentials today) live in .env, which is gitignored. Anything
# already present in the real environment wins, so the server can override.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:  # dotenv is optional; env vars still work without it
    pass


def _env_flag(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The literal below is the historical development key and stays as the default
# so nothing breaks; set SECRET_KEY in the environment on any real host.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-0=g)t-7njmyr6(5w%c(54$c859@x7z9ymxml-ow%n1o21(tsi2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_flag('DEBUG', True)

ALLOWED_HOSTS = [
    '68.183.93.246',
    'enpower.techinfinity.link',
    'www.enpower.techinfinity.link',
    'localhost',
    '127.0.0.1',
]

# Railway hands the service its own hostname, which changes when a domain is
# added or the service is renamed, so it cannot be hard-coded above.
_railway_host = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if _railway_host:
    ALLOWED_HOSTS.append(_railway_host)

# Anything else the host needs, comma separated.
ALLOWED_HOSTS += [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Django 4+ checks the Origin header on any HTTPS POST against this list, so a
# form on a domain missing from it fails CSRF with no useful error.
CSRF_TRUSTED_ORIGINS = [
    'https://enpower.techinfinity.link',
    'https://www.enpower.techinfinity.link',
]
if _railway_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_railway_host}')
CSRF_TRUSTED_ORIGINS += [o.strip() for o in
                         os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Railway terminates TLS at its edge and forwards over plain HTTP. Without
# this Django thinks every request is insecure, and builds http:// links.
if os.environ.get('RAILWAY_ENVIRONMENT') or _env_flag('TRUST_PROXY_SSL_HEADER'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [

    'enpower_skill_lab',

    'accounts',
    'schools',
    'competencies',
    'assessments',
    'lms',
    'attendance',
    'reports',

    # New role-based apps
    'superadmin',
    'coordinator',
    'school_admin',
    'teacher',
    'parent',
    'student',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves everything under STATIC_ROOT straight from this process. On the
    # droplet nginx does it; on Railway there is nothing in front, so without
    # this every stylesheet, script and the email logo 404s. Must sit directly
    # after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Keep signed-in HTML out of the browser cache — needs request.user, so it
    # must sit after AuthenticationMiddleware.
    'enpower_skill_lab.middleware.NoStoreHTMLMiddleware',
]

ROOT_URLCONF = 'enpower_skill_lab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'enpower_skill_lab', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school_admin.context_processors.school_admin_profile',
                'competencies.context_processors.nav_notifications',
                'parent.context_processors.parent_sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'enpower_skill_lab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite by default, which is what the droplet runs. Two environment
# variables can change that without touching this file:
#
#   DATABASE_URL   a full URL (Railway sets this when a Postgres service is
#                  attached) — takes precedence over everything else
#   SQLITE_PATH    where the SQLite file lives, so it can be pointed at a
#                  mounted volume on a host with an ephemeral filesystem
#
# On a container host the working directory is wiped on every deploy, so
# leaving SQLite at its default there loses the database on each push.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('SQLITE_PATH') or (BASE_DIR / 'db.sqlite3'),
    }
}

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600, conn_health_checks=True)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        # Compresses and fingerprints on collectstatic so files can be cached
        # hard. The non-manifest variant is used deliberately: the manifest
        # one raises at request time for any file a template references but
        # collectstatic did not find, which would take a page down over a
        # missing image.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# Media Files (User uploads like school logos, profile photos, etc.)
# MEDIA_ROOT is env-driven for the same reason as SQLITE_PATH: on a container
# host these are user uploads sitting on a disk that is wiped on every deploy,
# so it has to point at a mounted volume.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.environ.get('MEDIA_ROOT') or os.path.join(BASE_DIR, 'media')

# Whether Django itself should serve /media/. Turn this off on a host where
# nginx or a CDN handles it (the droplet does).
SERVE_MEDIA = _env_flag('SERVE_MEDIA', True)

# ── Email ───────────────────────────────────────────────────────────────
# Live sending goes through ZeptoMail. Every value is read from the
# environment (see .env.example) so the credentials never sit in the repo and
# so a developer can point at Mailtrap, or at the console backend, without
# touching this file.
#
# ZeptoMail expects the SMTP username `emailapikey` and the send-mail token as
# the password, and it will reject any From address outside a domain verified
# in the ZeptoMail console.

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.zeptomail.in')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_flag('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _env_flag('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'emailapikey')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'ENpower Skill Lab <noreply@enpowerskilllab.com>')

# Without this a hung SMTP server holds the request open until gunicorn kills
# the worker, which would take an onboarding form down with it.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

# Students and Parents receive system-generated login IDs handed to them by the
# school, so no credential email is sent to those two roles. Enforced centrally
# in competencies/emails.py — every send passes through that gate.
EMAIL_SUPPRESSED_ROLES = {
    r.strip().upper().replace(' ', '_')
    for r in os.environ.get('EMAIL_SUPPRESSED_ROLES', 'STUDENT,PARENT').split(',')
    if r.strip()
}

# Public address of the site. Emails leave the server and are opened elsewhere,
# so any link inside one has to be absolute and has to point at production.
SITE_URL = os.environ.get('SITE_URL', 'https://enpower.techinfinity.link').rstrip('/')

# How long a password reset link stays valid. Django's default is 3 days,
# which is long for a link that hands over an account; 24 hours is enough for
# someone to act on an email and short enough to limit a forwarded or leaked
# one. The token also dies on first use, or if the user logs in meanwhile.
PASSWORD_RESET_TIMEOUT = int(os.environ.get('PASSWORD_RESET_TIMEOUT', 60 * 60 * 24))

# Auth
LOGIN_URL = '/login/'
