
"""
Django settings for enpower_skill_lab project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets (SMTP credentials today) live in .env, which is gitignored. Anything
# already present in the real environment wins, so the server can override.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env', override=False)
except ImportError:  # dotenv is optional; env vars still work without it
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0=g)t-7njmyr6(5w%c(54$c859@x7z9ymxml-ow%n1o21(tsi2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '68.183.93.246',
    'enpower.techinfinity.link',
    'www.enpower.techinfinity.link',
    'localhost',
    '127.0.0.1']


# Application definition

INSTALLED_APPS = [

    'enpower_skill_lab',

    'accounts',
    'schools',
    'competencies',
    'assessments',
    'lms',
    'attendance',
    'reports',

    # New role-based apps
    'superadmin',
    'coordinator',
    'school_admin',
    'teacher',
    'parent',
    'student',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Keep signed-in HTML out of the browser cache — needs request.user, so it
    # must sit after AuthenticationMiddleware.
    'enpower_skill_lab.middleware.NoStoreHTMLMiddleware',
]

ROOT_URLCONF = 'enpower_skill_lab.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'enpower_skill_lab', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'school_admin.context_processors.school_admin_profile',
                'competencies.context_processors.nav_notifications',
                'parent.context_processors.parent_sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'enpower_skill_lab.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# Media Files (User uploads like school logos, profile photos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ── Email ───────────────────────────────────────────────────────────────
# Live sending goes through ZeptoMail. Every value is read from the
# environment (see .env.example) so the credentials never sit in the repo and
# so a developer can point at Mailtrap, or at the console backend, without
# touching this file.
#
# ZeptoMail expects the SMTP username `emailapikey` and the send-mail token as
# the password, and it will reject any From address outside a domain verified
# in the ZeptoMail console.

def _env_flag(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.zeptomail.in')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = _env_flag('EMAIL_USE_TLS', True)
EMAIL_USE_SSL = _env_flag('EMAIL_USE_SSL', False)
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'emailapikey')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'ENpower Skill Lab <noreply@enpowerskilllab.com>')

# Without this a hung SMTP server holds the request open until gunicorn kills
# the worker, which would take an onboarding form down with it.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))

# Students and Parents receive system-generated login IDs handed to them by the
# school, so no credential email is sent to those two roles. Enforced centrally
# in competencies/emails.py — every send passes through that gate.
EMAIL_SUPPRESSED_ROLES = {
    r.strip().upper().replace(' ', '_')
    for r in os.environ.get('EMAIL_SUPPRESSED_ROLES', 'STUDENT,PARENT').split(',')
    if r.strip()
}

# Public address of the site. Emails leave the server and are opened elsewhere,
# so any link inside one has to be absolute and has to point at production.
SITE_URL = os.environ.get('SITE_URL', 'https://enpower.techinfinity.link').rstrip('/')

# Auth
LOGIN_URL = '/login/'
