# Generated by Django 6.0.6 on 2026-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='program',
            field=models.CharField(blank=True, help_text='Program name (FSL / CSL plus / CSL foundation) — replaces "instrument"', max_length=50),
        ),
    ]
