# Generated by Django 6.0.6 on 2026-06-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_timetable_end_date_timetable_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='class_status',
            field=models.CharField(choices=[('held', 'Class Held'), ('cancelled', 'Class Cancelled')], default='held', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='attendance.timetable'),
        ),
    ]
