# Generated by Django 6.0.6 on 2026-08-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_class_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1),
        ),
    ]
