# Generated by Django 5.2.8 on 2026-10-06 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancerecord_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUploadSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_upload_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Upload — Last Seen',
                'verbose_name_plural': 'Project Uploads — Last Seen',
            },
        ),
    ]
