# Generated by Django 5.2.8 on 2026-10-07 11:18

import enpower_skill_lab.academic_year
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_projectuploadseen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], default=enpower_skill_lab.academic_year.current_academic_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='dailysessionfeedback',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], default=enpower_skill_lab.academic_year.current_academic_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='studentprojectupload',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], default=enpower_skill_lab.academic_year.current_academic_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='academic_year',
            field=models.CharField(choices=[('2023-2024', '2023-2024'), ('2024-2025', '2024-2025'), ('2025-2026', '2025-2026'), ('2026-2027', '2026-2027'), ('2027-2028', '2027-2028')], default=enpower_skill_lab.academic_year.current_academic_year, max_length=9),
        ),
    ]
